// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package database

import (
	"database/sql"
	"time"
)

type RefreshToken struct {
	Token     string
	CreatedAt string
	UpdatedAt string
	UserID    int64
	ExpiresAt string
	RevokedAt sql.NullString
}

type Role struct {
	ID    int64
	Title string
}

type User struct {
	ID              int64
	CreatedAt       string
	UpdatedAt       string
	Name            string
	Iin             string
	Phone           string
	DateOfBirth     string
	PasswordHash    string
	CurrentLocation string
}

type UsersRole struct {
	AddedAt time.Time
	UserID  int64
	RoleID  int64
}
