// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: users_roles.sql

package database

import (
	"context"
)

const addRole2User = `-- name: AddRole2User :exec
INSERT INTO users_roles(user_id, role_id)
VALUES (?, ?)
`

type AddRole2UserParams struct {
	UserID int64
	RoleID int64
}

func (q *Queries) AddRole2User(ctx context.Context, arg AddRole2UserParams) error {
	_, err := q.db.ExecContext(ctx, addRole2User, arg.UserID, arg.RoleID)
	return err
}

const removeRoleFromUser = `-- name: RemoveRoleFromUser :exec

DELETE FROM users_roles 
WHERE user_id = ? AND role_id = ?
`

type RemoveRoleFromUserParams struct {
	UserID int64
	RoleID int64
}

func (q *Queries) RemoveRoleFromUser(ctx context.Context, arg RemoveRoleFromUserParams) error {
	_, err := q.db.ExecContext(ctx, removeRoleFromUser, arg.UserID, arg.RoleID)
	return err
}

const removeRolesOfUser = `-- name: RemoveRolesOfUser :exec

DELETE FROM users_roles 
WHERE user_id = ?
`

func (q *Queries) RemoveRolesOfUser(ctx context.Context, userID int64) error {
	_, err := q.db.ExecContext(ctx, removeRolesOfUser, userID)
	return err
}
