basePath: /
definitions:
  database.Role:
    properties:
      id:
        type: integer
      title:
        type: string
    type: object
  views.CreateUserRequest:
    properties:
      current_location:
        type: string
      date_of_birth:
        type: string
      iin:
        type: string
      name:
        type: string
      password:
        type: string
      phone:
        type: string
    type: object
  views.ErrorResponse:
    properties:
      error:
        type: string
    type: object
  views.ResponseId:
    properties:
      id:
        type: integer
    type: object
  views.ResponseMessage:
    properties:
      message:
        type: string
    type: object
  views.SignInRequest:
    properties:
      password:
        type: string
      phone:
        type: string
    type: object
  views.TokensResponse:
    properties:
      access_token:
        type: string
      refresh_token:
        type: string
    type: object
  views.UpdateProfileRequest:
    properties:
      current_location:
        type: string
      date_of_birth:
        description: Email       string `json:"email"`
        type: string
      iin:
        type: string
      name:
        description: Id          int64     `json:"id"`
        type: string
      phone:
        type: string
    type: object
  views.UpdateUserRequest:
    properties:
      current_location:
        type: string
      date_of_birth:
        description: Email       string  `json:"email"`
        type: string
      iin:
        type: string
      name:
        description: Id          int64     `json:"id"`
        type: string
      phone:
        type: string
      role_ids:
        items:
          type: integer
        type: array
    type: object
  views.User:
    properties:
      date_of_birth:
        description: Email       string          `json:"email"`
        type: string
      id:
        type: integer
      iin:
        type: string
      name:
        type: string
      phone:
        type: string
      roles:
        items:
          $ref: '#/definitions/database.Role'
        type: array
    type: object
host: hackathon-2025-police-volunteers.onrender.com
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a sample server POLICE.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: VOLUNTEERS API
  version: "1.0"
paths:
  /:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/views.ResponseMessage'
        "500":
          description: Invalid file
          schema:
            $ref: '#/definitions/views.ErrorResponse'
      summary: Saying hello
      tags:
      - Tests
  /v1/auth/refresh:
    post:
      consumes:
      - application/json
      parameters:
      - description: Bearer RefreshToken
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/views.TokensResponse'
        "400":
          description: Couldn't find token
          schema:
            $ref: '#/definitions/views.ErrorResponse'
        "404":
          description: Couldn't find user
          schema:
            $ref: '#/definitions/views.ErrorResponse'
        "500":
          description: Couldn't create tokens
          schema:
            $ref: '#/definitions/views.ErrorResponse'
      summary: Refresh
      tags:
      - Auth
  /v1/auth/sign-in:
    post:
      consumes:
      - application/json
      parameters:
      - description: Authentication
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/views.SignInRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/views.TokensResponse'
        "400":
          description: Invalid Data
          schema:
            $ref: '#/definitions/views.ErrorResponse'
        "401":
          description: Incorrect email or password
          schema:
            $ref: '#/definitions/views.ErrorResponse'
        "404":
          description: Email not found
          schema:
            $ref: '#/definitions/views.ErrorResponse'
        "500":
          description: Couldn't create tokens
          schema:
            $ref: '#/definitions/views.ErrorResponse'
      summary: Sign In
      tags:
      - Auth
  /v1/auth/sign-out:
    post:
      consumes:
      - application/json
      parameters:
      - description: Bearer AccessToken
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "204":
          description: No Content
        "400":
          description: Couldn't find token
          schema:
            $ref: '#/definitions/views.ErrorResponse'
        "500":
          description: Couldn't revoke session
          schema:
            $ref: '#/definitions/views.ErrorResponse'
      summary: Sign Out
      tags:
      - Auth
  /v1/users:
    get:
      consumes:
      - application/json
      parameters:
      - description: Bearer AccessToken
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/views.User'
            type: array
        "401":
          description: No token Middleware
          schema:
            $ref: '#/definitions/views.ErrorResponse'
        "403":
          description: No Permission
          schema:
            $ref: '#/definitions/views.ErrorResponse'
        "404":
          description: Not found User Middleware
          schema:
            $ref: '#/definitions/views.ErrorResponse'
        "500":
          description: Couldn't Get users
          schema:
            $ref: '#/definitions/views.ErrorResponse'
      security:
      - Bearer: []
      summary: Get Users List
      tags:
      - Users
    post:
      consumes:
      - application/json
      parameters:
      - description: User data
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/views.CreateUserRequest'
      produces:
      - application/json
      responses:
        "201":
          description: OK
          schema:
            $ref: '#/definitions/views.ResponseId'
        "400":
          description: Invalid data
          schema:
            $ref: '#/definitions/views.ErrorResponse'
        "500":
          description: Couldn't hash password
          schema:
            $ref: '#/definitions/views.ErrorResponse'
      summary: Create user (Register)
      tags:
      - Users
  /v1/users/{id}:
    delete:
      consumes:
      - application/json
      parameters:
      - description: Bearer AccessToken
        in: header
        name: Authorization
        required: true
        type: string
      - description: id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/views.ResponseId'
        "400":
          description: Invalid data
          schema:
            $ref: '#/definitions/views.ErrorResponse'
        "401":
          description: No token Middleware
          schema:
            $ref: '#/definitions/views.ErrorResponse'
        "403":
          description: No Permission
          schema:
            $ref: '#/definitions/views.ErrorResponse'
        "404":
          description: Not found User Middleware
          schema:
            $ref: '#/definitions/views.ErrorResponse'
        "500":
          description: Couldn't delete user
          schema:
            $ref: '#/definitions/views.ErrorResponse'
      security:
      - Bearer: []
      summary: Delete user profile
      tags:
      - Users
    get:
      consumes:
      - application/json
      parameters:
      - description: Bearer AccessToken
        in: header
        name: Authorization
        required: true
        type: string
      - description: id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/views.User'
        "400":
          description: Invalid data
          schema:
            $ref: '#/definitions/views.ErrorResponse'
        "401":
          description: No token Middleware
          schema:
            $ref: '#/definitions/views.ErrorResponse'
        "403":
          description: No Permission
          schema:
            $ref: '#/definitions/views.ErrorResponse'
        "404":
          description: Not found User Middleware
          schema:
            $ref: '#/definitions/views.ErrorResponse'
        "500":
          description: Couldn't get user
          schema:
            $ref: '#/definitions/views.ErrorResponse'
      security:
      - Bearer: []
      summary: Get User
      tags:
      - Users
    put:
      consumes:
      - application/json
      parameters:
      - description: Bearer AccessToken
        in: header
        name: Authorization
        required: true
        type: string
      - description: id
        in: path
        name: id
        required: true
        type: integer
      - description: User data
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/views.UpdateUserRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Invalid data
          schema:
            $ref: '#/definitions/views.ErrorResponse'
        "401":
          description: No token Middleware
          schema:
            $ref: '#/definitions/views.ErrorResponse'
        "403":
          description: No Permission
          schema:
            $ref: '#/definitions/views.ErrorResponse'
        "404":
          description: Not found User Middleware
          schema:
            $ref: '#/definitions/views.ErrorResponse'
        "500":
          description: Couldn't update user data
          schema:
            $ref: '#/definitions/views.ErrorResponse'
      security:
      - Bearer: []
      summary: Update user
      tags:
      - Users
  /v1/users/profile:
    delete:
      consumes:
      - application/json
      parameters:
      - description: Bearer AccessToken
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/views.ResponseId'
        "401":
          description: No token Middleware
          schema:
            $ref: '#/definitions/views.ErrorResponse'
        "404":
          description: Not found User Middleware
          schema:
            $ref: '#/definitions/views.ErrorResponse'
        "500":
          description: Couldn't delete user
          schema:
            $ref: '#/definitions/views.ErrorResponse'
      security:
      - Bearer: []
      summary: Delete user profile
      tags:
      - Users
    get:
      consumes:
      - application/json
      parameters:
      - description: Bearer AccessToken
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/views.User'
        "401":
          description: No token Middleware
          schema:
            $ref: '#/definitions/views.ErrorResponse'
        "404":
          description: Not found User Middleware
          schema:
            $ref: '#/definitions/views.ErrorResponse'
        "500":
          description: Couldn't Get user
          schema:
            $ref: '#/definitions/views.ErrorResponse'
      security:
      - Bearer: []
      summary: Get User profile
      tags:
      - Users
    put:
      consumes:
      - application/json
      parameters:
      - description: Bearer AccessToken
        in: header
        name: Authorization
        required: true
        type: string
      - description: User data
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/views.UpdateProfileRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Invalid data
          schema:
            $ref: '#/definitions/views.ErrorResponse'
        "401":
          description: No token Middleware
          schema:
            $ref: '#/definitions/views.ErrorResponse'
        "404":
          description: Not found User Middleware
          schema:
            $ref: '#/definitions/views.ErrorResponse'
        "500":
          description: Couldn't update user data
          schema:
            $ref: '#/definitions/views.ErrorResponse'
      security:
      - Bearer: []
      summary: Update user profile
      tags:
      - Users
securityDefinitions:
  Bearer:
    description: Type "Bearer" followed by a space and JWT token.
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
